#!/bin/sh
vim Makefile \
	bucse-mount.c \
	destinations/dest.h \
	destinations/dest.c \
	destinations/dest_local.c \
	destinations/dest_ssh.c \
	encryption/encr.h \
	encryption/encr.c \
	encryption/encr_none.c \
	encryption/encr_aes.c \
	dynarray.h \
	dynarray.c \
	filesystem.h \
	filesystem.c \
	actions.h \
	actions.c \
	time.h \
	time.c \
	conf.h \
	conf.c \
	log.h \
	log.c \
	operations/operations.h \
	operations/operations.c \
	operations/getattr.h \
	operations/getattr.c \
	operations/flush.h \
	operations/flush.c \
	operations/readdir.h \
	operations/readdir.c \
	operations/open.h \
	operations/open.c \
	operations/create.h \
	operations/create.c \
	operations/release.h \
	operations/release.c \
	operations/read.h \
	operations/read.c \
	operations/write.h \
	operations/write.c \
	operations/unlink.h \
	operations/unlink.c \
	operations/mkdir.h \
	operations/mkdir.c \
	operations/rmdir.h \
	operations/rmdir.c \
	operations/truncate.h \
	operations/truncate.c \
	operations/rename.h \
	operations/rename.c \
	operations/init.h \
	operations/init.c \
	bucse-init.c \
	edit.sh \
	TODO
